# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:462.0.1@sha256:a96072e7bfad292451e62497c14a409f5ab298ee7905518820512dae3d3dc02d
RUN apt-get install -y netcat
