# gcloud sdk for pubsub emulator with netcat added for the startup health check
FROM google/cloud-sdk:459.0.0@sha256:8c326885cfcbd29ef9748b7a389e717aa24465cc1b6d6660f13cfd4101469394
RUN apt-get install -y netcat
